# coding: utf-8

"""
    ASET Indoor Climate Station

    Enter description here  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_sensor_data(self):
        """Test case for add_sensor_data

        Add new sensor data to the server  # noqa: E501
        """
        pass

    def test_get_sensor_data(self):
        """Test case for get_sensor_data

        Get all sensor data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
