# coding: utf-8

"""
    ASET Indoor Climate Station

    Enter description here  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sensor_data import SensorData  # noqa: E501
from swagger_client.rest import ApiException


class TestSensorData(unittest.TestCase):
    """SensorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensorData(self):
        """Test SensorData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sensor_data.SensorData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
